"""regulatory content ingestion tables

Revision ID: 36606e944171
Revises: d398dec852dd
Create Date: 2026-09-05 20:06:13.409820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36606e944171'
down_revision: Union[str, None] = 'd398dec852dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_framework_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_key', sa.String(length=64), nullable=False),
    sa.Column('framework_name', sa.String(length=255), nullable=False),
    sa.Column('framework_family', sa.String(length=64), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=128), nullable=False),
    sa.Column('framework_type', sa.String(length=96), nullable=False),
    sa.Column('version_label', sa.String(length=96), nullable=False),
    sa.Column('version_ordinal', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.String(length=32), nullable=True),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('application_dates', sa.JSON(), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('validation_version', sa.String(length=32), nullable=False),
    sa.Column('expected_counts', sa.JSON(), nullable=True),
    sa.Column('ingested_counts', sa.JSON(), nullable=True),
    sa.Column('published_counts', sa.JSON(), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('published_status', sa.String(length=24), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('blocking_reasons', sa.JSON(), nullable=True),
    sa.Column('source_manifest', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_key', 'version_label', name='uq_framework_version')
    )
    op.create_index(op.f('ix_regulatory_framework_versions_framework_key'), 'regulatory_framework_versions', ['framework_key'], unique=False)
    op.create_index(op.f('ix_regulatory_framework_versions_is_current'), 'regulatory_framework_versions', ['is_current'], unique=False)
    op.create_table('regulatory_ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_key', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(length=24), nullable=True),
    sa.Column('pipeline_stage', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('framework_version_id', sa.String(length=36), nullable=True),
    sa.Column('log', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_ingestion_runs_framework_key'), 'regulatory_ingestion_runs', ['framework_key'], unique=False)
    op.create_table('regulatory_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_key', sa.String(length=64), nullable=False),
    sa.Column('framework_family', sa.String(length=64), nullable=False),
    sa.Column('document_key', sa.String(length=96), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=128), nullable=False),
    sa.Column('document_type', sa.String(length=96), nullable=False),
    sa.Column('canonical_identifier', sa.String(length=128), nullable=True),
    sa.Column('official_url', sa.String(length=1000), nullable=False),
    sa.Column('machine_readable_url', sa.String(length=1000), nullable=True),
    sa.Column('source_format', sa.String(length=32), nullable=False),
    sa.Column('copyright_owner', sa.String(length=255), nullable=True),
    sa.Column('licence_name', sa.String(length=255), nullable=True),
    sa.Column('licence_url', sa.String(length=1000), nullable=True),
    sa.Column('commercial_reuse_allowed', sa.Boolean(), nullable=True),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=True),
    sa.Column('modification_allowed', sa.Boolean(), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=True),
    sa.Column('share_alike_required', sa.Boolean(), nullable=True),
    sa.Column('third_party_material_present', sa.Boolean(), nullable=True),
    sa.Column('licence_status', sa.String(length=48), nullable=False),
    sa.Column('licence_verified_at', sa.DateTime(), nullable=True),
    sa.Column('licence_evidence_url', sa.String(length=1000), nullable=True),
    sa.Column('attribution_statement', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.String(length=32), nullable=True),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('application_dates', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_key', 'document_key', name='uq_source_framework_document')
    )
    op.create_index(op.f('ix_regulatory_sources_framework_key'), 'regulatory_sources', ['framework_key'], unique=False)
    op.create_table('regulatory_applicability_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_key', sa.String(length=96), nullable=False),
    sa.Column('framework_key', sa.String(length=64), nullable=False),
    sa.Column('framework_version_id', sa.String(length=36), nullable=True),
    sa.Column('requirement_key', sa.String(length=128), nullable=True),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('subject_role', sa.String(length=96), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('exceptions', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=48), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('source_anchor_url', sa.String(length=1000), nullable=True),
    sa.Column('confidence', sa.String(length=24), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.String(length=32), nullable=True),
    sa.Column('effective_until', sa.String(length=32), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['framework_version_id'], ['regulatory_framework_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_applicability_rules_framework_key'), 'regulatory_applicability_rules', ['framework_key'], unique=False)
    op.create_index(op.f('ix_regulatory_applicability_rules_framework_version_id'), 'regulatory_applicability_rules', ['framework_version_id'], unique=False)
    op.create_index(op.f('ix_regulatory_applicability_rules_requirement_key'), 'regulatory_applicability_rules', ['requirement_key'], unique=False)
    op.create_index(op.f('ix_regulatory_applicability_rules_rule_key'), 'regulatory_applicability_rules', ['rule_key'], unique=False)
    op.create_table('regulatory_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_version_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=True),
    sa.Column('definition_available', sa.Boolean(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('source_anchor_url', sa.String(length=1000), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.String(length=32), nullable=True),
    sa.Column('effective_until', sa.String(length=32), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['framework_version_id'], ['regulatory_framework_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_definitions_framework_version_id'), 'regulatory_definitions', ['framework_version_id'], unique=False)
    op.create_index(op.f('ix_regulatory_definitions_term'), 'regulatory_definitions', ['term'], unique=False)
    op.create_table('regulatory_framework_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_version_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('layer', sa.String(length=24), nullable=False),
    sa.Column('check_key', sa.String(length=96), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['framework_version_id'], ['regulatory_framework_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_framework_validations_framework_version_id'), 'regulatory_framework_validations', ['framework_version_id'], unique=False)
    op.create_index(op.f('ix_regulatory_framework_validations_run_id'), 'regulatory_framework_validations', ['run_id'], unique=False)
    op.create_table('regulatory_source_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('retrieved_url', sa.String(length=1000), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('http_headers', sa.JSON(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('previous_sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('retrieval_status', sa.String(length=48), nullable=False),
    sa.Column('fixture_backed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_source_artifacts_sha256'), 'regulatory_source_artifacts', ['sha256'], unique=False)
    op.create_index(op.f('ix_regulatory_source_artifacts_source_id'), 'regulatory_source_artifacts', ['source_id'], unique=False)
    op.create_table('regulatory_source_change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('previous_sha256', sa.String(length=64), nullable=True),
    sa.Column('new_sha256', sa.String(length=64), nullable=True),
    sa.Column('previous_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('new_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('change_kind', sa.String(length=32), nullable=True),
    sa.Column('diff_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_source_change_events_source_id'), 'regulatory_source_change_events', ['source_id'], unique=False)
    op.create_table('regulatory_framework_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_version_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('node_type', sa.String(length=48), nullable=False),
    sa.Column('official_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_text_available', sa.Boolean(), nullable=True),
    sa.Column('platform_summary', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('source_anchor_url', sa.String(length=1000), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('cross_references', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['framework_version_id'], ['regulatory_framework_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['regulatory_framework_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['regulatory_source_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_fw_official', 'regulatory_framework_nodes', ['framework_version_id', 'official_id'], unique=False)
    op.create_index(op.f('ix_regulatory_framework_nodes_framework_version_id'), 'regulatory_framework_nodes', ['framework_version_id'], unique=False)
    op.create_index(op.f('ix_regulatory_framework_nodes_official_id'), 'regulatory_framework_nodes', ['official_id'], unique=False)
    op.create_index(op.f('ix_regulatory_framework_nodes_parent_id'), 'regulatory_framework_nodes', ['parent_id'], unique=False)
    op.create_table('regulatory_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_version_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('requirement_key', sa.String(length=128), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('source_parent_reference', sa.String(length=255), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_text_available', sa.Boolean(), nullable=True),
    sa.Column('normalized_requirement', sa.Text(), nullable=False),
    sa.Column('interpretation_label', sa.String(length=24), nullable=True),
    sa.Column('obligation_type', sa.String(length=48), nullable=False),
    sa.Column('subject_roles', sa.JSON(), nullable=True),
    sa.Column('who_is_obligated', sa.String(length=255), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('effective_from', sa.String(length=32), nullable=True),
    sa.Column('effective_until', sa.String(length=32), nullable=True),
    sa.Column('temporal_state', sa.String(length=32), nullable=True),
    sa.Column('applicability_logic', sa.JSON(), nullable=True),
    sa.Column('evidence_expectations', sa.JSON(), nullable=True),
    sa.Column('test_method', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('source_anchor_url', sa.String(length=1000), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('extraction_method', sa.String(length=32), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=96), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['framework_version_id'], ['regulatory_framework_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['regulatory_framework_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['regulatory_source_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_version_id', 'requirement_key', name='uq_requirement_key_per_version')
    )
    op.create_index(op.f('ix_regulatory_requirements_framework_version_id'), 'regulatory_requirements', ['framework_version_id'], unique=False)
    op.create_index(op.f('ix_regulatory_requirements_node_id'), 'regulatory_requirements', ['node_id'], unique=False)
    op.create_index(op.f('ix_regulatory_requirements_requirement_key'), 'regulatory_requirements', ['requirement_key'], unique=False)
    op.create_table('regulatory_requirement_control_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('control_code', sa.String(length=64), nullable=False),
    sa.Column('mapping_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['regulatory_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_requirement_control_maps_control_code'), 'regulatory_requirement_control_maps', ['control_code'], unique=False)
    op.create_index(op.f('ix_regulatory_requirement_control_maps_requirement_id'), 'regulatory_requirement_control_maps', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_requirement_control_maps_requirement_id'), table_name='regulatory_requirement_control_maps')
    op.drop_index(op.f('ix_regulatory_requirement_control_maps_control_code'), table_name='regulatory_requirement_control_maps')
    op.drop_table('regulatory_requirement_control_maps')
    op.drop_index(op.f('ix_regulatory_requirements_requirement_key'), table_name='regulatory_requirements')
    op.drop_index(op.f('ix_regulatory_requirements_node_id'), table_name='regulatory_requirements')
    op.drop_index(op.f('ix_regulatory_requirements_framework_version_id'), table_name='regulatory_requirements')
    op.drop_table('regulatory_requirements')
    op.drop_index(op.f('ix_regulatory_framework_nodes_parent_id'), table_name='regulatory_framework_nodes')
    op.drop_index(op.f('ix_regulatory_framework_nodes_official_id'), table_name='regulatory_framework_nodes')
    op.drop_index(op.f('ix_regulatory_framework_nodes_framework_version_id'), table_name='regulatory_framework_nodes')
    op.drop_index('ix_node_fw_official', table_name='regulatory_framework_nodes')
    op.drop_table('regulatory_framework_nodes')
    op.drop_index(op.f('ix_regulatory_source_change_events_source_id'), table_name='regulatory_source_change_events')
    op.drop_table('regulatory_source_change_events')
    op.drop_index(op.f('ix_regulatory_source_artifacts_source_id'), table_name='regulatory_source_artifacts')
    op.drop_index(op.f('ix_regulatory_source_artifacts_sha256'), table_name='regulatory_source_artifacts')
    op.drop_table('regulatory_source_artifacts')
    op.drop_index(op.f('ix_regulatory_framework_validations_run_id'), table_name='regulatory_framework_validations')
    op.drop_index(op.f('ix_regulatory_framework_validations_framework_version_id'), table_name='regulatory_framework_validations')
    op.drop_table('regulatory_framework_validations')
    op.drop_index(op.f('ix_regulatory_definitions_term'), table_name='regulatory_definitions')
    op.drop_index(op.f('ix_regulatory_definitions_framework_version_id'), table_name='regulatory_definitions')
    op.drop_table('regulatory_definitions')
    op.drop_index(op.f('ix_regulatory_applicability_rules_rule_key'), table_name='regulatory_applicability_rules')
    op.drop_index(op.f('ix_regulatory_applicability_rules_requirement_key'), table_name='regulatory_applicability_rules')
    op.drop_index(op.f('ix_regulatory_applicability_rules_framework_version_id'), table_name='regulatory_applicability_rules')
    op.drop_index(op.f('ix_regulatory_applicability_rules_framework_key'), table_name='regulatory_applicability_rules')
    op.drop_table('regulatory_applicability_rules')
    op.drop_index(op.f('ix_regulatory_sources_framework_key'), table_name='regulatory_sources')
    op.drop_table('regulatory_sources')
    op.drop_index(op.f('ix_regulatory_ingestion_runs_framework_key'), table_name='regulatory_ingestion_runs')
    op.drop_table('regulatory_ingestion_runs')
    op.drop_index(op.f('ix_regulatory_framework_versions_is_current'), table_name='regulatory_framework_versions')
    op.drop_index(op.f('ix_regulatory_framework_versions_framework_key'), table_name='regulatory_framework_versions')
    op.drop_table('regulatory_framework_versions')
    # ### end Alembic commands ###
