"""baseline schema

Revision ID: d398dec852dd
Revises: 
Create Date: 2026-09-05 09:28:00.274709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd398dec852dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicability_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('system_id', sa.String(length=36), nullable=True),
    sa.Column('system_name', sa.String(length=255), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('decision_status', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('eu_ai_act_classification', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('recommended_frameworks', sa.JSON(), nullable=True),
    sa.Column('required_controls', sa.JSON(), nullable=True),
    sa.Column('rules_fired', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('unresolved_questions', sa.JSON(), nullable=True),
    sa.Column('requires_legal_review', sa.Boolean(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('reviewer_decision', sa.String(length=50), nullable=True),
    sa.Column('reviewer_rationale', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('ruleset_version', sa.String(length=50), nullable=True),
    sa.Column('assessed_as_of_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicability_decisions_organization_id'), 'applicability_decisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_applicability_decisions_system_id'), 'applicability_decisions', ['system_id'], unique=False)
    op.create_index(op.f('ix_applicability_decisions_tenant_id'), 'applicability_decisions', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('customer_controls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('effectiveness', sa.String(length=50), nullable=True),
    sa.Column('implementation_notes', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_controls_control_id'), 'customer_controls', ['control_id'], unique=False)
    op.create_index(op.f('ix_customer_controls_organization_id'), 'customer_controls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customer_controls_tenant_id'), 'customer_controls', ['tenant_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('storage_backend', sa.String(length=20), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    op.create_table('incident_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=True),
    sa.Column('incident_title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('contained_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('affected_users_count', sa.Integer(), nullable=True),
    sa.Column('data_affected', sa.Boolean(), nullable=True),
    sa.Column('regulatory_reported', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_organization_id'), 'incident_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incident_reports_tenant_id'), 'incident_reports', ['tenant_id'], unique=False)
    op.create_table('policy_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_documents_organization_id'), 'policy_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_policy_documents_tenant_id'), 'policy_documents', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('models_provided', sa.JSON(), nullable=True),
    sa.Column('contract_status', sa.String(length=50), nullable=True),
    sa.Column('contract_owner', sa.String(length=255), nullable=True),
    sa.Column('vendor_owner', sa.String(length=255), nullable=True),
    sa.Column('contract_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('data_processing_role', sa.String(length=50), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.Column('data_residency', sa.JSON(), nullable=True),
    sa.Column('subprocessors', sa.JSON(), nullable=True),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('allows_customer_data_training', sa.Boolean(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('privacy_documentation_url', sa.String(length=500), nullable=True),
    sa.Column('security_documentation_url', sa.String(length=500), nullable=True),
    sa.Column('ai_governance_documentation_url', sa.String(length=500), nullable=True),
    sa.Column('incident_obligations', sa.Text(), nullable=True),
    sa.Column('business_continuity_plan', sa.Text(), nullable=True),
    sa.Column('exit_strategy', sa.Text(), nullable=True),
    sa.Column('risk_rating', sa.String(length=50), nullable=True),
    sa.Column('dpa_signed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('evidence_control_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('coverage_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_control_maps_control_id'), 'evidence_control_maps', ['control_id'], unique=False)
    op.create_index(op.f('ix_evidence_control_maps_evidence_id'), 'evidence_control_maps', ['evidence_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('headquarters_country', sa.String(length=100), nullable=True),
    sa.Column('countries_operating', sa.JSON(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('is_financial_institution', sa.Boolean(), nullable=True),
    sa.Column('is_critical_infrastructure', sa.Boolean(), nullable=True),
    sa.Column('eu_market_exposure', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('business_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('parent_business_unit_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_business_unit_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_units_organization_id'), 'business_units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_business_units_tenant_id'), 'business_units', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('ai_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_products_business_unit_id'), 'ai_products', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_ai_products_organization_id'), 'ai_products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_products_tenant_id'), 'ai_products', ['tenant_id'], unique=False)
    op.create_table('ai_systems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_purpose', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('business_unit', sa.String(length=100), nullable=True),
    sa.Column('business_unit_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('countries_deployed', sa.JSON(), nullable=True),
    sa.Column('user_countries', sa.JSON(), nullable=True),
    sa.Column('customer_countries', sa.JSON(), nullable=True),
    sa.Column('users_affected_count', sa.Integer(), nullable=True),
    sa.Column('internal_or_external', sa.String(length=50), nullable=True),
    sa.Column('ai_technology', sa.String(length=100), nullable=True),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('has_foundation_model', sa.Boolean(), nullable=True),
    sa.Column('is_fine_tuned', sa.Boolean(), nullable=True),
    sa.Column('uses_rag', sa.Boolean(), nullable=True),
    sa.Column('uses_traditional_ml', sa.Boolean(), nullable=True),
    sa.Column('uses_computer_vision', sa.Boolean(), nullable=True),
    sa.Column('uses_nlp', sa.Boolean(), nullable=True),
    sa.Column('is_generative_ai', sa.Boolean(), nullable=True),
    sa.Column('is_agentic_ai', sa.Boolean(), nullable=True),
    sa.Column('makes_autonomous_decisions', sa.Boolean(), nullable=True),
    sa.Column('human_in_the_loop', sa.Boolean(), nullable=True),
    sa.Column('processes_personal_data', sa.Boolean(), nullable=True),
    sa.Column('processes_sensitive_data', sa.Boolean(), nullable=True),
    sa.Column('processes_children_data', sa.Boolean(), nullable=True),
    sa.Column('processes_biometric_data', sa.Boolean(), nullable=True),
    sa.Column('training_data_sources', sa.Text(), nullable=True),
    sa.Column('employment_impact', sa.Boolean(), nullable=True),
    sa.Column('credit_impact', sa.Boolean(), nullable=True),
    sa.Column('health_impact', sa.Boolean(), nullable=True),
    sa.Column('insurance_impact', sa.Boolean(), nullable=True),
    sa.Column('education_impact', sa.Boolean(), nullable=True),
    sa.Column('critical_infrastructure_impact', sa.Boolean(), nullable=True),
    sa.Column('law_enforcement_relevance', sa.Boolean(), nullable=True),
    sa.Column('decision_impact', sa.String(length=100), nullable=True),
    sa.Column('human_oversight', sa.String(length=100), nullable=True),
    sa.Column('autonomy_level', sa.String(length=50), nullable=True),
    sa.Column('uses_external_api', sa.Boolean(), nullable=True),
    sa.Column('deployment_environment', sa.String(length=100), nullable=True),
    sa.Column('cloud_provider', sa.String(length=100), nullable=True),
    sa.Column('apis_exposed', sa.JSON(), nullable=True),
    sa.Column('production_status', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('risk_classification', sa.String(length=50), nullable=True),
    sa.Column('eu_ai_act_classification', sa.String(length=50), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('applicable_frameworks', sa.JSON(), nullable=True),
    sa.Column('architecture_description', sa.Text(), nullable=True),
    sa.Column('data_flows_description', sa.Text(), nullable=True),
    sa.Column('known_limitations', sa.Text(), nullable=True),
    sa.Column('monitoring_configuration', sa.JSON(), nullable=True),
    sa.Column('kill_switch_implemented', sa.Boolean(), nullable=True),
    sa.Column('model_card_url', sa.String(length=500), nullable=True),
    sa.Column('system_card_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['ai_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_systems_business_unit_id'), 'ai_systems', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_ai_systems_lifecycle_status'), 'ai_systems', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_ai_systems_organization_id'), 'ai_systems', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_systems_product_id'), 'ai_systems', ['product_id'], unique=False)
    op.create_index(op.f('ix_ai_systems_tenant_id'), 'ai_systems', ['tenant_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=True),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('hosted_location', sa.String(length=100), nullable=True),
    sa.Column('is_proprietary', sa.Boolean(), nullable=True),
    sa.Column('is_foundation_model', sa.Boolean(), nullable=True),
    sa.Column('is_fine_tuned', sa.Boolean(), nullable=True),
    sa.Column('hosting_type', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('training_data_info', sa.Text(), nullable=True),
    sa.Column('known_risks', sa.JSON(), nullable=True),
    sa.Column('approved_uses', sa.JSON(), nullable=True),
    sa.Column('prohibited_uses', sa.JSON(), nullable=True),
    sa.Column('customer_data_handling', sa.Text(), nullable=True),
    sa.Column('data_retention_policy', sa.Text(), nullable=True),
    sa.Column('deployment_locations', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_system_id'), 'ai_models', ['system_id'], unique=False)
    op.create_index(op.f('ix_ai_models_tenant_id'), 'ai_models', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_models_vendor_id'), 'ai_models', ['vendor_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('framework_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('readiness_percentage', sa.Float(), nullable=True),
    sa.Column('implementation_score', sa.Float(), nullable=True),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_organization_id'), 'assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assessments_system_id'), 'assessments', ['system_id'], unique=False)
    op.create_index(op.f('ix_assessments_tenant_id'), 'assessments', ['tenant_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=True),
    sa.Column('risk_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('threat_source', sa.String(length=255), nullable=True),
    sa.Column('inherent_likelihood', sa.Integer(), nullable=True),
    sa.Column('inherent_impact', sa.Integer(), nullable=True),
    sa.Column('inherent_score', sa.Integer(), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_impact', sa.Integer(), nullable=True),
    sa.Column('residual_score', sa.Integer(), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('mitre_atlas_technique', sa.String(length=100), nullable=True),
    sa.Column('owasp_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_organization_id'), 'risks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risks_system_id'), 'risks', ['system_id'], unique=False)
    op.create_index(op.f('ix_risks_tenant_id'), 'risks', ['tenant_id'], unique=False)
    op.create_table('ai_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('parent_agent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('orchestrator', sa.String(length=100), nullable=True),
    sa.Column('identity', sa.String(length=255), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('has_code_execution', sa.Boolean(), nullable=True),
    sa.Column('has_database_access', sa.Boolean(), nullable=True),
    sa.Column('has_payment_access', sa.Boolean(), nullable=True),
    sa.Column('has_email_access', sa.Boolean(), nullable=True),
    sa.Column('has_git_access', sa.Boolean(), nullable=True),
    sa.Column('has_git_write_access', sa.Boolean(), nullable=True),
    sa.Column('has_external_web_access', sa.Boolean(), nullable=True),
    sa.Column('has_external_communication_access', sa.Boolean(), nullable=True),
    sa.Column('can_invoke_other_agents', sa.Boolean(), nullable=True),
    sa.Column('accesses_pii', sa.Boolean(), nullable=True),
    sa.Column('autonomy_level', sa.String(length=50), nullable=True),
    sa.Column('human_approval_required', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_config', sa.JSON(), nullable=True),
    sa.Column('environments', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approved_use_cases', sa.JSON(), nullable=True),
    sa.Column('prohibited_actions', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['ai_agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agents_model_id'), 'ai_agents', ['model_id'], unique=False)
    op.create_index(op.f('ix_ai_agents_parent_agent_id'), 'ai_agents', ['parent_agent_id'], unique=False)
    op.create_index(op.f('ix_ai_agents_system_id'), 'ai_agents', ['system_id'], unique=False)
    op.create_index(op.f('ix_ai_agents_tenant_id'), 'ai_agents', ['tenant_id'], unique=False)
    op.create_table('ai_system_model_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_system_model_links_model_id'), 'ai_system_model_links', ['model_id'], unique=False)
    op.create_index(op.f('ix_ai_system_model_links_system_id'), 'ai_system_model_links', ['system_id'], unique=False)
    op.create_index(op.f('ix_ai_system_model_links_tenant_id'), 'ai_system_model_links', ['tenant_id'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_responses_assessment_id'), 'assessment_responses', ['assessment_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=True),
    sa.Column('control_id', sa.String(length=50), nullable=True),
    sa.Column('risk_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_organization_id'), 'findings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_findings_system_id'), 'findings', ['system_id'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_table('model_version_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_version_history_model_id'), 'model_version_history', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_version_history_tenant_id'), 'model_version_history', ['tenant_id'], unique=False)
    op.create_table('remediation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_tasks_finding_id'), 'remediation_tasks', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediation_tasks_tenant_id'), 'remediation_tasks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_tasks_tenant_id'), table_name='remediation_tasks')
    op.drop_index(op.f('ix_remediation_tasks_finding_id'), table_name='remediation_tasks')
    op.drop_table('remediation_tasks')
    op.drop_index(op.f('ix_model_version_history_tenant_id'), table_name='model_version_history')
    op.drop_index(op.f('ix_model_version_history_model_id'), table_name='model_version_history')
    op.drop_table('model_version_history')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_system_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_organization_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_assessment_responses_assessment_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index(op.f('ix_ai_system_model_links_tenant_id'), table_name='ai_system_model_links')
    op.drop_index(op.f('ix_ai_system_model_links_system_id'), table_name='ai_system_model_links')
    op.drop_index(op.f('ix_ai_system_model_links_model_id'), table_name='ai_system_model_links')
    op.drop_table('ai_system_model_links')
    op.drop_index(op.f('ix_ai_agents_tenant_id'), table_name='ai_agents')
    op.drop_index(op.f('ix_ai_agents_system_id'), table_name='ai_agents')
    op.drop_index(op.f('ix_ai_agents_parent_agent_id'), table_name='ai_agents')
    op.drop_index(op.f('ix_ai_agents_model_id'), table_name='ai_agents')
    op.drop_table('ai_agents')
    op.drop_index(op.f('ix_risks_tenant_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_system_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_organization_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_assessments_tenant_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_system_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_organization_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_ai_models_vendor_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_tenant_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_system_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_ai_systems_tenant_id'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_product_id'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_organization_id'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_lifecycle_status'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_business_unit_id'), table_name='ai_systems')
    op.drop_table('ai_systems')
    op.drop_index(op.f('ix_ai_products_tenant_id'), table_name='ai_products')
    op.drop_index(op.f('ix_ai_products_organization_id'), table_name='ai_products')
    op.drop_index(op.f('ix_ai_products_business_unit_id'), table_name='ai_products')
    op.drop_table('ai_products')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_business_units_tenant_id'), table_name='business_units')
    op.drop_index(op.f('ix_business_units_organization_id'), table_name='business_units')
    op.drop_table('business_units')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_evidence_control_maps_evidence_id'), table_name='evidence_control_maps')
    op.drop_index(op.f('ix_evidence_control_maps_control_id'), table_name='evidence_control_maps')
    op.drop_table('evidence_control_maps')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_policy_documents_tenant_id'), table_name='policy_documents')
    op.drop_index(op.f('ix_policy_documents_organization_id'), table_name='policy_documents')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_incident_reports_tenant_id'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_organization_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_customer_controls_tenant_id'), table_name='customer_controls')
    op.drop_index(op.f('ix_customer_controls_organization_id'), table_name='customer_controls')
    op.drop_index(op.f('ix_customer_controls_control_id'), table_name='customer_controls')
    op.drop_table('customer_controls')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_applicability_decisions_tenant_id'), table_name='applicability_decisions')
    op.drop_index(op.f('ix_applicability_decisions_system_id'), table_name='applicability_decisions')
    op.drop_index(op.f('ix_applicability_decisions_organization_id'), table_name='applicability_decisions')
    op.drop_table('applicability_decisions')
    # ### end Alembic commands ###
